---
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.4
  ruby: circleci/ruby@2.0.1

executors:
  rails-executor:
    docker:
      - image: cimg/ruby:3.2.2-browsers
        environment:
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: theodinproject_test
    working_directory: ~/theodinproject

commands:
  build-app:
    description: Building app
    steps:
      - run: gem install bundler:2.4.13
      - restore_cache:
          name: Restore bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - save_cache:
          name: Store bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          name: Store yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:schema:load

jobs:
  tests:
    executor: rails-executor
    steps:
      - checkout
      - browser-tools/install-chrome:
          chrome-version: "116.0.5845.96" # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
          replace-existing: true # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
      - browser-tools/install-chromedriver
      - run:
          command:
            google-chrome --version
            chromedriver --version
          name: Check install
      - build-app
      - run: yarn test
      - ruby/rspec-test
  linters:
    executor: rails-executor
    steps:
      - checkout
      - build-app
      - run: bundle exec rubocop
      - run: bundle exec erblint --lint-all
      - run: yarn run eslint
  seeds:
    executor: rails-executor
    steps:
      - checkout
      - build-app
      - run:
          name: Seeds
          command: bin/rails db:seed

workflows:
  build:
    jobs:
      - tests
      - linters
      - seeds
